INFO: 2019-06-17 09:27:24,539: perform_upgrade() 'Last run version was 0.7.2 or earlier, current version is 0.7.2'
INFO: 2019-06-17 09:27:24,785: process_command() 'Received command: []'
INFO: 2019-06-17 09:27:24,832: load_banned() 'Missing or invalid banned URLs list, no URLs will be banned'
INFO: 2019-06-17 09:27:25,171: load() 'Jumble loading'
INFO: 2019-06-17 09:27:25,172: _walk_modules() 'Jumble loading module in __init__ from /usr/share/variety/plugins/__init__.py'
INFO: 2019-06-17 09:27:25,175: _walk_modules() 'Jumble loading module in QuotesDaddySource from /usr/share/variety/plugins/quotes/QuotesDaddySource.py'
INFO: 2019-06-17 09:27:25,177: load() 'Jumble found plugin class: <class 'QuotesDaddySource.QuotesDaddySource'>: {'name': 'QuotesDaddy', 'description': "Fetches quotes from QuotesDaddy's daily quotes RSS feed.\nDoes not support searching by tags or authors.", 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2019-06-17 09:27:25,179: _walk_modules() 'Jumble loading module in QuotationsPageSource from /usr/share/variety/plugins/quotes/QuotationsPageSource.py'
INFO: 2019-06-17 09:27:25,335: load() 'Jumble found plugin class: <class 'QuotationsPageSource.QuotationsPageSource'>: {'name': 'TheQuotationsPage.com', 'description': 'Fetches quotes from TheQuotationsPage.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2019-06-17 09:27:25,336: _walk_modules() 'Jumble loading module in __init__ from /usr/share/variety/plugins/quotes/__init__.py'
INFO: 2019-06-17 09:27:25,338: _walk_modules() 'Jumble loading module in LocalFilesSource from /usr/share/variety/plugins/quotes/LocalFilesSource.py'
INFO: 2019-06-17 09:27:25,351: load() 'Jumble found plugin class: <class 'LocalFilesSource.LocalFilesSource'>: {'name': 'Local text files', 'description': 'Displays quotes, defined in local text files.\nPut your own txt files in: ~/.config/variety/pluginconfig/quotes/.\nThe file format is:\n\nquote -- author\n.\nsecond quote -- another author\n.\netc...\n\nExample: http://rvelthuis.de/zips/quotes.txt', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2019-06-17 09:27:25,352: _walk_modules() 'Jumble loading module in GoodreadsSource from /usr/share/variety/plugins/quotes/GoodreadsSource.py'
INFO: 2019-06-17 09:27:25,353: load() 'Jumble found plugin class: <class 'GoodreadsSource.GoodreadsSource'>: {'name': 'Goodreads', 'description': 'Fetches quotes from Goodreads.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2019-06-17 09:27:25,357: reload_config() 'Creating new downloader for type 6, location Random wallpapers from Desktoppr.co'
INFO: 2019-06-17 09:27:25,358: log_options() 'Loaded options:'
INFO: 2019-06-17 09:27:25,358: log_options() 'change_enabled = True'
INFO: 2019-06-17 09:27:25,358: log_options() 'change_interval = 1800'
INFO: 2019-06-17 09:27:25,358: log_options() 'change_on_start = False'
INFO: 2019-06-17 09:27:25,358: log_options() 'clipboard_enabled = False'
INFO: 2019-06-17 09:27:25,358: log_options() 'clipboard_hosts = ['wallhaven.cc', 'wallpapers.net', 'flickr.com', 'imgur.com', 'deviantart.com', 'interfacelift.com', 'vladstudio.com', 'imageshack.us', 'deviantart.net', 'imageshack.com']'
INFO: 2019-06-17 09:27:25,358: log_options() 'clipboard_use_whitelist = True'
INFO: 2019-06-17 09:27:25,358: log_options() 'clock_date_font = Ubuntu Condensed, 30'
INFO: 2019-06-17 09:27:25,358: log_options() 'clock_enabled = False'
INFO: 2019-06-17 09:27:25,358: log_options() 'clock_filter = -density 100 -font `fc-match -f '%{file[0]}' '%CLOCK_FONT_NAME'` -pointsize %CLOCK_FONT_SIZE -gravity SouthEast -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+108] '%H:%M' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+110] '%H:%M' -font `fc-match -f '%{file[0]}' '%DATE_FONT_NAME'` -pointsize %DATE_FONT_SIZE -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+58] '%A, %B %d' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+60] '%A, %B %d''
INFO: 2019-06-17 09:27:25,358: log_options() 'clock_font = Ubuntu Condensed, 70'
INFO: 2019-06-17 09:27:25,358: log_options() 'configfile = /home/wg/.config/variety/variety.conf'
INFO: 2019-06-17 09:27:25,358: log_options() 'copyto_enabled = False'
INFO: 2019-06-17 09:27:25,358: log_options() 'copyto_folder = Default'
INFO: 2019-06-17 09:27:25,359: log_options() 'desired_color = [160, 160, 160]'
INFO: 2019-06-17 09:27:25,359: log_options() 'desired_color_enabled = False'
INFO: 2019-06-17 09:27:25,359: log_options() 'download_enabled = True'
INFO: 2019-06-17 09:27:25,359: log_options() 'download_folder = /home/wg/.config/variety/Downloaded'
INFO: 2019-06-17 09:27:25,359: log_options() 'download_interval = 60'
INFO: 2019-06-17 09:27:25,359: log_options() 'favorites_folder = /home/wg/.config/variety/Favorites'
INFO: 2019-06-17 09:27:25,359: log_options() 'favorites_operations = [['Downloaded', 'Copy'], ['Fetched', 'Move'], ['Others', 'Copy']]'
INFO: 2019-06-17 09:27:25,359: log_options() 'fetched_folder = /home/wg/.config/variety/Fetched'
INFO: 2019-06-17 09:27:25,359: log_options() 'filters = [[False, 'Keep original', ''], [False, 'Grayscale', '-type Grayscale'], [False, 'Heavy blur', '-blur 120x40'], [False, 'Soft blur', '-blur 20x7'], [False, 'Oil painting', '-paint 8'], [False, 'Pencil sketch', '-colorspace gray \\( +clone -tile ~/.config/variety/pencil_tile.png -draw "color 0,0 reset" +clone +swap -compose color_dodge -composite \\) -fx \'u*.2+v*.8\''], [False, 'Pointilism', '-spread 10 -noise 3'], [False, 'Pixellate', '-scale 3% -scale 3333%']]'
INFO: 2019-06-17 09:27:25,359: log_options() 'icon = Light'
INFO: 2019-06-17 09:27:25,359: log_options() 'lightness_enabled = False'
INFO: 2019-06-17 09:27:25,359: log_options() 'lightness_mode = 0'
INFO: 2019-06-17 09:27:25,359: log_options() 'min_rating = 4'
INFO: 2019-06-17 09:27:25,359: log_options() 'min_rating_enabled = False'
INFO: 2019-06-17 09:27:25,359: log_options() 'min_size = 80'
INFO: 2019-06-17 09:27:25,359: log_options() 'min_size_enabled = True'
INFO: 2019-06-17 09:27:25,359: log_options() 'quota_enabled = True'
INFO: 2019-06-17 09:27:25,360: log_options() 'quota_size = 500'
INFO: 2019-06-17 09:27:25,360: log_options() 'quotes_authors = '
INFO: 2019-06-17 09:27:25,360: log_options() 'quotes_bg_color = [80, 80, 80]'
INFO: 2019-06-17 09:27:25,360: log_options() 'quotes_bg_opacity = 55'
INFO: 2019-06-17 09:27:25,361: log_options() 'quotes_change_enabled = False'
INFO: 2019-06-17 09:27:25,361: log_options() 'quotes_change_interval = 300'
INFO: 2019-06-17 09:27:25,362: log_options() 'quotes_disabled_sources = ['QuotesDaddy']'
INFO: 2019-06-17 09:27:25,362: log_options() 'quotes_enabled = False'
INFO: 2019-06-17 09:27:25,362: log_options() 'quotes_favorites_file = /home/wg/.config/variety/favorite_quotes.txt'
INFO: 2019-06-17 09:27:25,362: log_options() 'quotes_font = Bitstream Charter 30'
INFO: 2019-06-17 09:27:25,362: log_options() 'quotes_hpos = 100'
INFO: 2019-06-17 09:27:25,362: log_options() 'quotes_tags = '
INFO: 2019-06-17 09:27:25,362: log_options() 'quotes_text_color = [255, 255, 255]'
INFO: 2019-06-17 09:27:25,362: log_options() 'quotes_text_shadow = False'
INFO: 2019-06-17 09:27:25,362: log_options() 'quotes_vpos = 40'
INFO: 2019-06-17 09:27:25,362: log_options() 'quotes_width = 70'
INFO: 2019-06-17 09:27:25,362: log_options() 'safe_mode = False'
INFO: 2019-06-17 09:27:25,363: log_options() 'slideshow_custom_enabled = False'
INFO: 2019-06-17 09:27:25,363: log_options() 'slideshow_custom_folder = /home/wg/Pictures'
INFO: 2019-06-17 09:27:25,363: log_options() 'slideshow_downloads_enabled = False'
INFO: 2019-06-17 09:27:25,363: log_options() 'slideshow_fade = 0.4'
INFO: 2019-06-17 09:27:25,363: log_options() 'slideshow_favorites_enabled = True'
INFO: 2019-06-17 09:27:25,363: log_options() 'slideshow_mode = Fullscreen'
INFO: 2019-06-17 09:27:25,363: log_options() 'slideshow_monitor = All'
INFO: 2019-06-17 09:27:25,364: log_options() 'slideshow_pan = 0.05'
INFO: 2019-06-17 09:27:25,364: log_options() 'slideshow_seconds = 6.0'
INFO: 2019-06-17 09:27:25,364: log_options() 'slideshow_sort_order = Random'
INFO: 2019-06-17 09:27:25,364: log_options() 'slideshow_sources_enabled = True'
INFO: 2019-06-17 09:27:25,364: log_options() 'slideshow_zoom = 0.2'
INFO: 2019-06-17 09:27:25,364: log_options() 'smart_enabled = False'
INFO: 2019-06-17 09:27:25,364: log_options() 'smart_notice_shown = True'
INFO: 2019-06-17 09:27:25,364: log_options() 'smart_register_shown = False'
INFO: 2019-06-17 09:27:25,364: log_options() 'sources = [[True, 3, 'The Favorites folder'], [False, 4, 'The Fetched folder'], [True, 2, '/usr/share/backgrounds'], [True, 6, 'Random wallpapers from Desktoppr.co'], [False, 15, 'Bing Photo of the Day'], [False, 16, 'High-resolution photos from Unsplash.com'], [False, 8, "NASA's Astronomy Picture of the Day"], [False, 11, 'World Sunlight Map - live wallpaper from Die.net'], [False, 7, 'user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;']]'
INFO: 2019-06-17 09:27:25,364: log_options() 'stats_enabled = True'
INFO: 2019-06-17 09:27:25,364: log_options() 'stats_notice_shown = True'
INFO: 2019-06-17 09:27:25,364: log_options() 'sync_enabled = True'
INFO: 2019-06-17 09:27:25,364: log_options() 'use_landscape_enabled = True'
INFO: 2019-06-17 09:27:25,364: reload_config() 'No need to clear prepared queue'
INFO: 2019-06-17 09:27:25,364: load_last_change_time() 'Change interval < 6 hours, ignore persisted last_change_time, wait initially the whole interval: 1800'
INFO: 2019-06-17 09:27:25,364: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:27:25,370: regular_change_thread() 'regular_change thread running'
INFO: 2019-06-17 09:27:25,370: prepare_thread() 'Prepare thread running'
INFO: 2019-06-17 09:27:25,370: prepare_thread() 'Prepared buffer contains 0 images'
INFO: 2019-06-17 09:27:25,371: prepare_thread() 'Preparing some images'
INFO: 2019-06-17 09:27:25,377: update_indicator_icon() 'Creating indicator'
WARNING: 2019-06-17 09:27:25,430: create_menu() 'Variety Slideshow is not installed. This is an optional extension adding pan-and-zoom slideshows to Variety: see https://github.com/peterlevi/variety-slideshow for details'
INFO: 2019-06-17 09:27:25,432: create_indicator() 'indicator backend: fallback tray'
INFO: 2019-06-17 09:27:25,466: do_set_wp() 'Calling do_set_wp with /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg, time: 1560734845.4668515'
INFO: 2019-06-17 09:27:25,528: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:27:25,592: set_from_theme_icon() 'Showing status icon variety-indicator from GTK theme'
INFO: 2019-06-17 09:27:25,605: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
ERROR: 2019-06-17 09:27:25,633: image_ok() 'Error in image_ok for file /home/wg/.config/variety/Downloaded/Desktoppr/wxp__5_.jpg'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 1482, in image_ok
    i = PILImage.open(img)
  File "/usr/lib/python3.7/site-packages/PIL/Image.py", line 2705, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/home/wg/.config/variety/Downloaded/Desktoppr/wxp__5_.jpg'
ERROR: 2019-06-17 09:27:25,649: image_ok() 'Error in image_ok for file /home/wg/.config/variety/Downloaded/Desktoppr/2560x1600__4_.jpg'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 1482, in image_ok
    i = PILImage.open(img)
  File "/usr/lib/python3.7/site-packages/PIL/Image.py", line 2705, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/home/wg/.config/variety/Downloaded/Desktoppr/2560x1600__4_.jpg'
INFO: 2019-06-17 09:27:25,746: prepare_thread() 'After search prepared buffer contains 98 images'
INFO: 2019-06-17 09:27:26,971: reload() 'Reloading preferences dialog'
INFO: 2019-06-17 09:27:45,393: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-06-17 09:27:55,789: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 307, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='tiny.cc', port=80): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Read timed out. (read timeout=5)
INFO: 2019-06-17 09:28:25,385: purge_downloaded() 'Refreshed download folder size: 86 mb'
INFO: 2019-06-17 09:28:25,386: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:28:25,824: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
INFO: 2019-06-17 09:28:26,954: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/173354'
INFO: 2019-06-17 09:28:26,954: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/22c527f52719e5756af195f9498f485e647742e5/oboi_s_prekrasnymi_ugolkami_prirody_205_131.jpg'
INFO: 2019-06-17 09:28:26,954: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/oboi_s_prekrasnymi_ugolkami_prirody_205_131.jpg'
INFO: 2019-06-17 09:28:30,354: save_locally() 'Download complete'
INFO: 2019-06-17 09:28:30,355: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:28:30,359: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/oboi_s_prekrasnymi_ugolkami_prirody_205_131.jpg to prepared_from_downloads queue'
ERROR: 2019-06-17 09:28:31,800: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f66df3ea5f8>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f66df3ea5f8>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f66df3ea5f8>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2019-06-17 09:29:01,830: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-06-17 09:29:07,032: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f66df61c4a8>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f66df61c4a8>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f66df61c4a8>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2019-06-17 09:29:25,374: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:29:26,423: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/29681'
INFO: 2019-06-17 09:29:26,423: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/6b635be56a1ed2a1a1fd5f27160126b9b98fe612/idhbt_-_imgur.jpg'
INFO: 2019-06-17 09:29:26,423: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/idhbt_-_imgur.jpg'
INFO: 2019-06-17 09:29:27,835: save_locally() 'Download complete'
INFO: 2019-06-17 09:29:27,836: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:29:27,839: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/idhbt_-_imgur.jpg to prepared_from_downloads queue'
INFO: 2019-06-17 09:29:37,063: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-06-17 09:29:43,091: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f66df61c978>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f66df61c978>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f66df61c978>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2019-06-17 09:30:13,119: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2019-06-17 09:30:18,283: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 165, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f66df61e748>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f66df61e748>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/variety/VarietyWindow.py", line 939, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 593, in fetch_json
    return Util.request(url, data).json()
  File "/usr/lib/python3.7/site-packages/variety/Util.py", line 571, in request
    timeout=timeout)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f66df61e748>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2019-06-17 09:30:25,375: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:30:26,393: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/40793'
INFO: 2019-06-17 09:30:26,393: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/44e7f063396485d03b10f90996f6446e76d9a6c1/f068c012771b921356ac105909210e12.jpg'
INFO: 2019-06-17 09:30:26,393: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/f068c012771b921356ac105909210e12.jpg'
INFO: 2019-06-17 09:30:31,262: save_locally() 'Download complete'
INFO: 2019-06-17 09:30:31,262: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:30:31,266: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/f068c012771b921356ac105909210e12.jpg to prepared_from_downloads queue'
INFO: 2019-06-17 09:31:25,376: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:31:27,002: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/455383'
INFO: 2019-06-17 09:31:27,003: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/e7f016ecbce5a8fbd0cd2bd9e981da8edc7fb01e/wallpaper-1975827.png'
INFO: 2019-06-17 09:31:27,003: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/wallpaper-1975827.png'
INFO: 2019-06-17 09:31:38,676: save_locally() 'Download complete'
INFO: 2019-06-17 09:31:38,676: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:31:38,681: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/wallpaper-1975827.png to prepared_from_downloads queue'
INFO: 2019-06-17 09:32:25,376: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:32:26,758: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/238703'
INFO: 2019-06-17 09:32:26,758: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/3cb7e9faa78b280b318f2d03954c9f0ff9610002/143d8707ede12ccd10dc4f58e1c6ceb1.jpg'
INFO: 2019-06-17 09:32:26,758: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/143d8707ede12ccd10dc4f58e1c6ceb1.jpg'
INFO: 2019-06-17 09:32:27,839: save_locally() 'Download complete'
INFO: 2019-06-17 09:32:27,839: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:32:27,844: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/143d8707ede12ccd10dc4f58e1c6ceb1.jpg to prepared_from_downloads queue'
INFO: 2019-06-17 09:33:25,376: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:33:26,563: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/172060'
INFO: 2019-06-17 09:33:26,563: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/f7b422ef96dec84d194af6053f9a932423571d22/wallpaper-2250505.jpg'
INFO: 2019-06-17 09:33:26,563: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/wallpaper-2250505.jpg'
INFO: 2019-06-17 09:33:29,454: save_locally() 'Download complete'
INFO: 2019-06-17 09:33:29,454: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:33:29,459: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/wallpaper-2250505.jpg to prepared_from_downloads queue'
INFO: 2019-06-17 09:34:25,377: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:34:26,748: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/254800'
INFO: 2019-06-17 09:34:26,749: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/e4cef1bab5992d4619ea5ea31932eec9b1e33018/bfbc2game_2012-06-24_11-10-36-44.jpg'
INFO: 2019-06-17 09:34:26,749: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/bfbc2game_2012-06-24_11-10-36-44.jpg'
INFO: 2019-06-17 09:34:28,217: save_locally() 'Download complete'
INFO: 2019-06-17 09:34:28,218: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:34:28,222: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/bfbc2game_2012-06-24_11-10-36-44.jpg to prepared_from_downloads queue'
INFO: 2019-06-17 09:35:22,420: on_show_origin() 'Opening url: https://www.desktoppr.co/wallpapers/180950'
INFO: 2019-06-17 09:35:25,378: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:35:26,850: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/547788'
INFO: 2019-06-17 09:35:26,850: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/82eb9e8cfd686ecd46c090b0882075eea59edf96/13993012547.jpg'
INFO: 2019-06-17 09:35:26,850: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/13993012547.jpg'
INFO: 2019-06-17 09:35:29,584: save_locally() 'Download complete'
INFO: 2019-06-17 09:35:29,584: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:35:29,596: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/13993012547.jpg to prepared_from_downloads queue'
INFO: 2019-06-17 09:36:25,378: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:36:26,931: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/20110'
INFO: 2019-06-17 09:36:26,931: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/267ea4e7626d4e559ebe731ddb238a86715f5e37/1225960992832.jpg'
INFO: 2019-06-17 09:36:26,931: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/1225960992832.jpg'
INFO: 2019-06-17 09:36:30,677: save_locally() 'Download complete'
INFO: 2019-06-17 09:36:30,677: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:36:30,683: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/1225960992832.jpg to prepared_from_downloads queue'
INFO: 2019-06-17 09:37:25,378: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:37:26,603: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/142662'
INFO: 2019-06-17 09:37:26,603: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/189908a0fd03252c1290e58c245ca76eb18d8368/5630550406_aa742c8bfe_o.jpg'
INFO: 2019-06-17 09:37:26,603: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/5630550406_aa742c8bfe_o.jpg'
INFO: 2019-06-17 09:37:27,941: save_locally() 'Download complete'
INFO: 2019-06-17 09:37:27,941: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:37:27,946: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/5630550406_aa742c8bfe_o.jpg to prepared_from_downloads queue'
INFO: 2019-06-17 09:38:25,378: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:38:26,725: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/35234'
INFO: 2019-06-17 09:38:26,725: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/3b0d4cf8d1fd7acbe5bd79a4904bd426f4eb2256/wwdc2012_1920x1200_vignette.png'
INFO: 2019-06-17 09:38:26,725: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/wwdc2012_1920x1200_vignette.png'
INFO: 2019-06-17 09:38:30,496: save_locally() 'Download complete'
INFO: 2019-06-17 09:38:30,496: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:38:30,500: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/wwdc2012_1920x1200_vignette.png to prepared_from_downloads queue'
INFO: 2019-06-17 09:39:25,378: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:39:26,610: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/172295'
INFO: 2019-06-17 09:39:26,610: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/7030a6a6296073e613e00a4a169ccc662fb84e4a/wallpaper-2188674.jpg'
INFO: 2019-06-17 09:39:26,610: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/wallpaper-2188674.jpg'
INFO: 2019-06-17 09:39:28,996: save_locally() 'Download complete'
INFO: 2019-06-17 09:39:28,996: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:39:29,000: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/wallpaper-2188674.jpg to prepared_from_downloads queue'
INFO: 2019-06-17 09:40:25,379: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:40:27,079: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/202551'
INFO: 2019-06-17 09:40:27,079: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/31ba5c29edd8943c21ca3f783d5d5873aff27d67/6.jpg'
INFO: 2019-06-17 09:40:27,079: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/6.jpg'
INFO: 2019-06-17 09:40:29,723: save_locally() 'Download complete'
INFO: 2019-06-17 09:40:29,724: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:40:29,727: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/6.jpg to prepared_from_downloads queue'
INFO: 2019-06-17 09:41:25,379: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:41:26,549: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/171224'
INFO: 2019-06-17 09:41:26,549: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/c46067c7c577dde1ee37665f439f6dc8fc8fbbb0/androidsphere.jpg'
INFO: 2019-06-17 09:41:26,550: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/androidsphere.jpg'
INFO: 2019-06-17 09:41:27,181: save_locally() 'Download complete'
INFO: 2019-06-17 09:41:27,181: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:41:27,185: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/androidsphere.jpg to prepared_from_downloads queue'
INFO: 2019-06-17 09:42:25,380: download_one() 'Downloading a random image from desktoppr.co'
INFO: 2019-06-17 09:42:26,810: save_locally() 'Origin URL: https://www.desktoppr.co/wallpapers/135759'
INFO: 2019-06-17 09:42:26,810: save_locally() 'Image URL: http://a.desktopprassets.com/wallpapers/979f21d3b02cfca9dcb217681b274c28b352bef1/bad.jpg'
INFO: 2019-06-17 09:42:26,810: save_locally() 'Local name: /home/wg/.config/variety/Downloaded/Desktoppr/bad.jpg'
INFO: 2019-06-17 09:42:30,435: save_locally() 'Download complete'
INFO: 2019-06-17 09:42:30,436: update_indicator() 'Setting file info to: /home/wg/.config/variety/Downloaded/Desktoppr/2009-12-25_12.36.38.jpg'
INFO: 2019-06-17 09:42:30,439: download_one_from() 'Adding downloaded file /home/wg/.config/variety/Downloaded/Desktoppr/bad.jpg to prepared_from_downloads queue'
INFO: 2019-06-17 09:43:25,380: download_one() 'Downloading a random image from desktoppr.co'
